server:
  contextPath: /
  port: 8080
  connection-timeout: 180000
spring:
  application.name: library
  datasource:
    url: jdbc:mysql://localhost:3306/libraryv1?useSSL=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      jdbc:
        batch_size: 20
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  http.multipart:
    max-request-size: ${MAX_HTTP_REQUEST_SIZE:20MB}
    max-file-size: ${MAX_HTTP_FILE_SIZE:20MB}
#liquibase:
#  change-log: classpath:db-changelog.yaml